

version: "3.9"

networks:
  getir-network:
    driver: bridge

volumes:
  getir-mongo-data:
    name: getir-mongo-data

services:
  getir-mongo:
    image: mongo:4.4.4-bionic
    volumes:
      - getir-mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    ports:
      - "27017:27017"
    networks:
      - getir-network
