version: "3.9"

networks:
  getir-network:
    driver: bridge

volumes:
  getir-rd67-data:
    name: getir-rd67-data

services:

  getir-rd67:
    container_name: getir-rd67
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    ports:
      - "8005:8005"
    volumes:
      - getir-rd67-data:/app/rd67
    networks:
      - getir-network
    environment:
      - NODE_ENV=production
